### PR TITLE
Add CI and fix some style issues

### PR DESCRIPTION
**Pull request by llllllllll**
Uses github actions to run the tests for each pull request. Updates the tests and some code to fix the flake8 violations. Updates the tests to be more focused. Please refer to the individual commit messages for more information.

NOTE: the diff looks _very_ large. This is because this PR adds a few more example beatmap files. The actual code change is fairly small (~150 lines +-)

### CODE REVIEW

**Comment by jxu** [comment]
I'll have to look into how Github Actions works. As far as I can tell everything else is just style which I probably should've followed (my naming systems are kinda ad-hoc)

**Comment by llllllllll** [comment]
Yeah, most stuff is just small whitespace and line length issues. Also instead of `assert x == False`, you should just use `assert not x` because it is a bit more permissive and reads a bit nicer.

The only structural change is to use the `example_data` machinery for the test data. These are beatmaps and now collections that come with every install of slider. This makes it easy to write docs that need a beatmap because we know users will always have these available. There is a bit of existing machinery for loading these out of the package data so they get put in the correct place even when installing from pypi.

**Comment by jxu** [comment]
Ok so I assume we want to merge this before adding more tests?

**Comment by llllllllll** [comment]
I think that will make it easier for reviewers to see that the tests run. Also, people wont need to make style comments that `flake8` can flag automatically. It may also make it easier for people who want to make a small change and not set up the full development environment.

The only open pr currently is @InvisibleSymbol's #67. I am not sure if they are comfortable rebasing against this change. I could either:

- wait to merge this until their change goes in
- talk through handling this kind of rebase
- rebase and push to the branch for them

Let me know what is best or easiest for you all.

**Comment by InvisibleSymbol** [comment]
Personally I would be fine with either you or me rebasing #67 after merging this.
Would make sense to fix the tests in #67 directly instead of adding more tests and then changing them here again.

**Comment by llllllllll** [comment]
Okay, I will merge now. If you want to rebase your other PR go for it. If you decide you want me to do it or run into issues rebasing let me know and I can help.

**Pull request merged**
