### PR TITLE
Fix BPM calculation for inheriting timing points

### PR DESCRIPTION
**Pull request by de-odex**
forgot to rename commit to:
"FIX: BPM calculation for inheriting timing points"

### CODE REVIEW

**Comment by llllllllll** [comment]
Thanks for fixing this! Do you have an example beatmap and time where the BPM was incorrect but is now fixed?

**Comment by de-odex** [comment]
err no i dont, but it was based on https://osu.ppy.sh/help/wiki/osu!_File_Formats/Osu_(file_format)#timing-points

**Comment by blimmo** [comment]
As I understand it, this commit is changing `ms_per_beat` for inherited timing points to refer to the actual number rather than the value in the .osu file (which is a percentage of the parent's). 

I think this *is* an improvement because according to the wiki, inherited timing points don't actually just change the slider velocity, they change the length of the beat (although that might be equivalent for how we've used it?).

I'm not sure if the old slider parsing code is right anymore, but I think it is affected by the proposed changes so probably needs a change.

**Comment by de-odex** [comment]
oh yikes, this is what a rebase can do huh

**Pull request closed without merging**
