### PR TITLE
get_center fix for long sliders

### PR DESCRIPTION
**Pull request by blimmo**
Fixes the overflow error in `get_center` for long sliders (#25)

### CODE REVIEW

**Comment by llllllllll** [comment]
Great find! This explains why we are seeing different results because this defaults to int64 on gnu+linux.

**Comment by llllllllll** [comment]
Actually, should this be `float64`? Control points don't need to have integer values, right?

**Comment by blimmo** [comment]
I've never seen one with a non-integral value but you might be right, you've probably looked at more sliders than me

**Comment by llllllllll** [comment]
The control points in general do no need to. I have seen Perfect curves at +-10. For bezier they definitely don't always fit in the grid.

Either way it probably doesn't hurt to make these floats just in case.

**Comment by blimmo** [comment]
I'm not sure we need to support 10e13, do float64s support that large?

**Comment by llllllllll** [comment]
float64 can hold values much larger than int64, you lose some precision as the numbers get massive, though float64 can perfectly represent integers up to 2 ** 53 which is larger than 1e14.

**Pull request merged**
